//API assignment from June 2, 2022 Class 39
const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())

const presidents = {
    'unknown' : {
        'Number' : 'unknown',
        'Term' : 'unknown',
        'Party' : 'unknown',
        'Birth State' : 'unknown',
        'Facts' : 'unknown',
        'Image' : 'unknown',
    },
    'george washington' : {
        'Number' : 1,
        'Term' : 'April 30, 1789 - March 4, 1797',
        'Party' : 'Federalist',
        'Birth State' : 'Virginia',
        'Facts' : 'Revolutionary War hero was an enthusiastic dog breeder, particularly  of hunting hounds, to which he gave names like “Sweet Lips” and “Drunkard.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/george-washington.jpg',
    },
    'john adams' : {
        'Mumber' : 2,
        'Term' : 'March 4, 1797 - March 4, 1801',
        'Party' : 'Federalist',
        'Birth State' : 'Massachusetts',
        'Facts' : 'Exchanged with his wife Abigail more than 1,100 letters over the course of their lengthy relationship.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/john-adams.jpg',
    },
    'thomas jefferson' : {
        'Number' : 3,
        'Term' : 'March 4, 1801 - March 4, 1809',
        'Party' : 'Democratic-Republican',
        'Birth State' : 'Virginia',
        'Facts' : 'The principal author of the Declaration of Independence who loved science, technology and innovation.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/thomas-jefferson.jpg',
    },
    'james madison' : {
        'Number' : 4,
        'Term' : 'March 4, 1809 - March 4, 1817',
        'Party' : 'Democratic-Republican',
        'Birth State' : 'Virginia',
        'Facts' : 'Madison was the shortest president at 5 feet 4 inches and weighed barely over 100 pounds.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/james-madison.jpg',
    },
    'james monroe' : {
        'Number' : 5,
        'Term' : 'March 4, 1817 - March 4, 1825',
        'Party' : 'Democratic-Republican',
        'Birth State' : 'Virginia',
        'Facts' : 'Other than Washington, Monroe was the only President to ever run essentially unopposed, coasting to re-election in the 1820 race.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/james-monroe.jpg',
    },
    'john quincy adams' : {
        'Number' : 6,
        'Term' : 'March 4, 1825 - March 4, 1829',
        'Party' : 'Democratic-Republican/National Republican',
        'Birth State' : 'Massachusetts',
        'Facts' : 'Adams argued a famous Supreme Court case that freed the captive Africans who had rebelled aboard the Amistad slave ship.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/john-quincy-adams.jpg',
    },
    'andrew jackson' : {
        'Number' : 7,
        'Term' : 'March 4, 1829 - March 4, 1837',
        'Party' : 'Democratic',
        'Birth State' : 'South Carolina',
        'Facts' : 'Founder of the Democratic Party and for his support of individual liberty',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/andrew-jackson.jpg',
    },
    'martin van buren' : {
        'Number' : 8,
        'Term' : 'March 4, 1837 - March 4, 1841',
        'Party' : 'Whig',
        'Birth State' : 'New York',
        'Facts' : 'Van Buren was the first president to be born an American. All previous Presidents were originally British subjects, having been born prior to 1776.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/martin-van-buren.jpg',
    },
    'william harrison' : {
        'Number' : 9,
        'Term' : 'March 4, 1841 - April 4, 1841',
        'Party' : 'Whig',
        'Birth State' : 'South Carolina',
        'Facts' : 'Harrison lasted only 32 days in office, the shortest stint of any President.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/william-harrison.jpg',
    },
    'john tyler' : {
        'Number' : 10,
        'Term' : 'April 4, 1841 - March 4, 1845',
        'Party' : 'Democratic',
        'Birth State' : 'Virginia',
        'Facts' : 'He was the first President who was not elected',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/john-tyler.jpg',
    },
    'james polk' : {
        'Number' : 11,
        'Term' : 'March 4, 1845 - March 4, 1849',
        'Party' : 'Democratic',
        'Birth State' : 'North Carolina',
        'Facts' : 'Often referred to as the first “dark horse” President, Polk was the last strong President until the Civil War.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/james-knox-polk.jpg',
    },
    'zachary taylor' : {
        'Number' : 12,
        'Term' : 'March 4, 1849 - July 9, 1850',
        'Party' : 'Whig',
        'Birth State' : 'Virgina',
        'Facts' : '“Old Rough and Ready” never voted in an election prior to being on the ballot himself.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/zachary-taylor.gif',
    },
    'millard fillmore' : {
        'Number' : 13,
        'Term' : 'July 9, 1850 - March 4, 1853',
        'Party' : 'Democratic',
        'Birth State' : 'New York',
        'Facts' : 'Fillmore was the last Whig President; the party imploded soon after he left office.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/millard-fillmore.jpg',
    },
    'franklin pierce' : {
        'Number' : 14,
        'Term' : 'March 4, 1853 - March 4, 1857',
        'Party' : 'Democratic',
        'Birth State' : 'New Hampshire',
        'Facts' : 'The only president from New Hampshire also attended college in New England—Bowdoin College in Brunswick, Maine.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/franklin-pierce.jpg',
    },
    'james buchanan ' : {
        'Number' : 15,
        'Term' : 'March 4, 1857 - March 4, 1861',
        'Party' : 'Democratic',
        'Birth State' : 'Pennsylvania',
        'Facts' : 'While serving as minister to Great Britain, Buchanan helped draft the 1854 Ostend Manifesto, which advocated for an American invasion of Cuba',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/james-buchanan.jpg',
    },
    'abraham lincoln' : {
        'Number' : 16,
        'Term' : 'July 9, 1850 - March 4, 1853',
        'Party' : 'Republican',
        'Birth State' : 'Kentucky',
        'Facts' : '“Honest Abe,” the tallest president at 6 feet 4 inches, may have had Marfan Syndrome, a genetic disorder that causes people to be very tall, thin and long limbed',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/abraham-lincoln.png',
    },
    'andrew johnson ' : {
        'Number' : 17,
        'Term' : 'April 15, 1865 - March 4, 1869',
        'Party' : 'Democratic',
        'Birth State' : 'North Carolina',
        'Facts' : 'Though one of the few Presidents without a pet, Johnson apparently cared for a family of White House mice, which he called “the little fellows.”',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/andrew-johnson.jpg',
    },
    'ulysses grant' : {
        'Number' : 18,
        'Term' : 'March 4, 1869 - March 4, 1877',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Grant was invited to join Abraham Lincoln at Fords Theatre on the fateful evening of April 14, 1865, but was forced to decline after he and his wife made plans to visit their children in New Jersey.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/ulysses-grant.jpg',
    },
    'rutherford hayes' : {
        'Number' : 19,
        'Term' : 'March 4, 1877 - March 4, 1881',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Hayes was the first President to have a telephone in the White House.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/rutherford-hayes.jpg',
    },
    'james garfield' : {
        'Number' : 20,
        'Term' : 'March 4, 1881 - September 19, 1881',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Garfield (who was the first known left-handed President) was elected to the U.S. Senate, but he never served as Ohio senator because he then won the Republican nomination for president.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/james-garfield.jpg',
    },
    'chester arthur ' : {
        'Number' : 21,
        'Term' : 'September 19, 1881 - March 4, 1885',
        'Party' : 'Republican',
        'Birth State' : 'Vermont',
        'Facts' : 'Arthur was named in honor of Chester Abell, the doctor who delivered him.',
    'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/chester-arthur.jpg',
    },
    'grover cleveland' : {
        'Number' : 22,
        'Term' : 'March 4, 1885 - March 4, 1889',
        'Party' : 'Democratic',
        'Birth State' : 'New Jersey',
        'Facts' : 'The only President to has ever served non-consecutive terms',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/grover-cleveland.jpg',
    },
    'benjamin harrison' : {
        'Number' : 23,
        'Term' : 'March 4, 1889 - March 4, 1893',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Harrison was the first president to hire a female White House staffer.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/benjamin-harrison.jpg',
    },
    'grover cleveland' : {
        'Number' : 24,
        'Term' : 'March 4, 1893 - March 4, 1897',
        'Party' : 'Democratic',
        'Birth State' : 'New Jersey',
        'Facts' : 'The only President to has ever served non-consecutive terms',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/grover-cleveland.jpg',
    },
    'william mcKinley' : {
        'Number' : 25,
        'Term' : 'March 4, 1897 - September 14, 1901',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'McKinleys likeness appears on the $500 bill, which was discontinued in 1969.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/william-mckinley.jpg',
    },
    'theodore roosevelt' : {
        'Number' : 26,
        'Term' : 'July 9, 1850 - March 4, 1853',
        'Party' : 'Republican',
        'Birth State' : 'New York',
        'Facts' : 'Roosevelt was the youngest president, taking office at age 42.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/theodore-roosevelt.jpg',
    },
    'william taft' : {
        'Number' : 27,
        'Term' : 'March 4, 1909 - March 4, 1913',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Famous for his corpulence, Taft was the first president to hurl the ceremonial first pitch at a Major League Baseball game.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/william-howard-taft.jpg',
    },
    'woodrow wilson' : {
        'Number' : 28,
        'Term' : 'March 4, 1913 - March 4, 1921',
        'Party' : 'Democratic',
        'Birth State' : 'Virginia',
        'Facts' : 'In a 1914 proclamation, Wilson officially established the second Sunday in May as Mothers Day.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/woodrow-wilson.jpg',
    },
    'warren harding' : {
        'Number' : 29,
        'Term' : 'March 4, 1921 - August 2, 1923',
        'Party' : 'Republican',
        'Birth State' : 'Ohio',
        'Facts' : 'Harding signed the Budget and Accounting Act, which established the first formal budgeting process and created the Bureau of the Budget.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/warren-harding.jpg',
    },
    'calvin coolidge' : {
        'Number' : 30,
        'Term' : 'August 2, 1923 - March 4, 1929',
        'Party' : 'Republican',
        'Birth State' : 'Vermont',
        'Facts' : 'A quiet man, Coolidge purportedly replied, “You lose,” to a visitor who bet she could get at least three words out of him.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/calvin-coolidge.jpg',
    },
    'herbert hoover' : {
        'Number' : 31,
        'Term' : 'March 4, 1929 - March 4, 1933',
        'Party' : 'Republican',
        'Birth State' : 'Iowa',
        'Facts' : 'Hoover was the first president to hail from west of the Mississippi River.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/herbert-clark-hoover.jpeg',
    },
    'franklin roosevelt' : {
        'Number' : 32,
        'Term' : 'July 9, 1850 - March 4, 1853',
        'Party' : 'Democratic',
        'Birth State' : 'New York',
        'Facts' : 'The longest-serving commander-in-chief claimed to be distantly related to 11 other presidents, including his fifth cousin Theodore Roosevelt.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/f-d-roosevelt.jpg',
    },
    'harry truman' : {
        'Number' : 33,
        'Term' : 'April 12, 1945 - January 20, 1953',
        'Party' : 'Democratic',
        'Birth State' : 'Missouri',
        'Facts' : 'The “S” in Harry S. Truman was just an initial; it did not stand for any name',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/harry-s-truman.jpg',
    },
    'dwight eisenhower' : {
        'Number' : 34,
        'Term' : 'January 20, 1953 - January 20, 1961',
        'Party' : 'Republican',
        'Birth State' : 'Texas',
        'Facts' : 'World War II hero “Ike” was the first president to ride in a helicopter.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/dwight-d-eisenhower.jpg',
    },
    'john kennedy' : {
        'Number' : 35,
        'Term' : 'January 20, 1961 - November 22, 1963',
        'Party' : 'Democratic',
        'Birth State' : 'Massachusetts',
        'Facts' : 'After being injured and honorably discharged in World War II, John F. Kennedy was briefly employed as a journalist during the waning weeks of the war.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/j-f-kennedy.jpg',
    },
    'lyndon johnson ' : {
        'Number' : 36,
        'Term' : 'November 22, 1963 - January 20, 1969',
        'Party' : 'Democratic',
        'Birth State' : 'Texas',
        'Facts' : 'Johnsons first career was as a teacher. He worked at a school near the U.S.-Mexico border for four years before launching a career in politics.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/lyndon-b-johnson.jpg',
    },
    'richard nixon' : {
        'Number' : 37,
        'Term' : 'January 20, 1969 - August 9, 1974',
        'Party' : 'Republican',
        'Birth State' : 'California',
        'Facts' : 'Nixon became such a skillful poker player while stationed in the Solomon Islands during World War II that his winnings helped launch his political career upon his return to the United States.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/r-m-nixon.jpg',
    },
    'gerald ford' : {
        'Number' : 38,
        'Term' : 'August 9, 1974 - January 20, 1977',
        'Party' : 'Republican',
        'Birth State' : 'Nebraska',
        'Facts' : 'A star football player at the University of Michigan, Ford turned down offers from both the Detroit Lions and Green Bay Packers.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/g-r-ford.jpg',
    },
    'jimmy carter' : {
        'Number' : 39,
        'Term' : 'January 20, 1977 - January 20, 1981',
        'Party' : 'Democratic',
        'Birth State' : 'Georgia',
        'Facts' : 'In 1953, Carter gave up his successful military career to move back to Georgia and work on the family peanut farm.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/jimmy-carter.jpg',
    },
    'ronald reagan ' : {
        'Number' : 40,
        'Term' : 'January 20, 1981 - January 20, 1989',
        'Party' : 'Republican',
        'Birth State' : 'Illinois',
        'Facts' : 'Reagan worked as a lifeguard and sportscaster before becoming an actor and, later, a politician.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/ronald-reagan.png',
    },
    'george hw bush ' : {
        'Number' : 41,
        'Term' : 'January 20, 1989 - January 20, 1993',
        'Party' : 'Republican',
        'Birth State' : 'Massachusetts',
        'Facts' : 'While a student at Yale University, Bush was captain of the baseball team and met Babe Ruth.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/george-h-w-bush.jpg',
    },
    'bill clinton' : {
        'Number' : 42,
        'Term' : 'January 20, 1993 - January 20, 2001',
        'Party' : 'Democratic',
        'Birth State' : 'Arkansas',
        'Facts' : 'Clinton played the saxophone and famously performed on the Arsenio Hall Show when he was a candidate for president.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/bill-clinton.jpg',
    },
    'george w bush' : {
        'Number' : 43,
        'Term' : 'January 20, 2001 - January 20, 2009',
        'Party' : 'Republican',
        'Birth State' : 'Connecticut',
        'Facts' : 'Bush took up oil painting, exhibiting his work at the Museum of the Southwest in Texas.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/george-w-bush.jpg',
    },
    'barack obama' : {
        'Number' : 44,
        'Term' : 'January 20, 2009 - January 20, 2017',
        'Party' : 'Democratic',
        'Birth State' : 'Hawaii',
        'Facts' : 'Prior to becoming the first African American President, Obama won two Grammy Awards for “Best Spoken Word Album.”',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/barack-obama.jpg',
    },
    'donald trump' : {
        'Number' : 45,
        'Term' : 'January 20, 2017 - January 20, 2021',
        'Party' : 'Republican',
        'Birth State' : 'New York',
        'Facts' : 'Before becoming President, Trump was a real estate developer, entrepreneur and host of the NBC reality show, "The Apprentice."',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/donald-trump.jpg',
    },
    'joseph biden' : {
        'Number' : 46,
        'Term' : 'January 20, 2021 - present',
        'Party' : 'Democratic',
        'Birth State' : 'Pennsylvania',
        'Facts' : 'Biden overcame a debilitating childhood stutter after enduring bullying over the condition in grade school.',
        'Image' : 'https://www.examsegg.com/wp-content/uploads/2017/06/joe-biden-new-president-of-america-scaled.jpg',
    },
    'name' : {
        'Number' : 47,
        'Term' : 'July 9, 1850 - March 4, 1853',
        'Party' : '',
        'Birth State' : '',
        'Facts' : 'none',
        'Image' : '',
    },

}

app.get('/', (request, response) => {
    response.sendFile(__dirname + '/index.html')
})

app.get('/api/:name', (request, response) => {
    const presName = request.params.name.toLowerCase()
        if (presidents[presName]){
            response.json(presidents[presName])
        }else{
            response.json(presidents['unknown'])
        }
})

app.listen(process.env.PORT || PORT, () => {
    console.log(`The presAPI server is working like a charm on port ${PORT}!!!`)
})